---
- name: "Run reboot Python script"
  hosts: "linux"
  gather_facts: "false"
  tasks:
    - name: "Restart Linux Hosts"
      script: "files/reboot.py"
    - name: "Wait for the reboot to complete"
      wait_for_connection:
        delay: 60
        timeout: 300
    - name: Gather facts for first time
      setup:
    - name: "Sending an e-mail after reboot"
      script: "files/mailreboot.py
  
